FROM debian:stretch

COPY etc/apt/preferences.d/dnsdist /etc/apt/preferences.d/dnsdist
ENV APT_KEY_DONT_WARN_ON_DANGEROUS_USAGE=DontWarn
RUN apt-get update
RUN apt-get install -y curl gnupg supervisor
RUN echo 'deb [arch=amd64] http://repo.powerdns.com/debian stretch-dnsdist-master main' > /etc/apt/sources.list.d/pdns.list
RUN curl https://repo.powerdns.com/CBC8B383-pub.asc |  apt-key add - && \
  apt-get update && \
  apt-get install -y dnsdist && \
  rm -rf /var/lib/apt/lists/*

COPY dnsdist-entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

ENTRYPOINT ["/entrypoint.sh"]
